config/routes.rb
Rails.application.routes.draw do

  resources :recepcionista
  resources :consulta do
    resources :relatorio_consulta
  end
  resources :pacientes do
    resources :endereco_paciente
  end
  resources :home
  resources :admin do
    resources :dentista
  end
  get "login", to: "login#new"
  post "login", to: "login#create"
  delete"logout", to: "login#destroy"
  get "acesso_paciente", to: "acesso_paciente#new"
  post "acesso_paciente", to: "acesso_paciente#create"
  delete"paciente_logout", to: "acesso_paciente#destroy"
  post "admin/:admin_id/dentista/new", to: "dentista#create"
  post "/consulta/:consultum_id/relatorio_consulta/new", to: "relatorio_consulta#create"
  get "acesso_recepcionista", to: "acesso_recepcionista#new"
  post "acesso_recepcionista", to: "acesso_recepcionista#create"
  delete"recepcionista_logout", to: "acesso_recepcionista#destroy"


  root to: "home#index"
end

app/controllers/acesso_paciente_controller.rb
class AcessoPacienteController < ApplicationController

  def new
  end

  def create
    @paciente= Paciente.find_by(cpf: params[:cpf])
    validar_paciente
  end

  def destroy
    session[:paciente_id] = nil
    flash[:success]= "desconectado com sucesso"
    redirect_to root_path
  end

  def validar_paciente
    if @paciente.present?
      session[:paciente_id] = @paciente.id
      flash[:success]= "logado com sucesso"
      render :'acesso_paciente/index'

    else
      flash[:alert]= "CPF não cadastrado"
      render :'acesso_paciente/new'
    end
  end
end

app/views/acesso_paciente/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>
  <%="Bem vindo, " + @paciente.nome + "!" %><br><br>
</h1>

<div id="pacientes">

    <p>
      <%= link_to "Ver mais informações", @paciente %><br><br>
      <%= link_to "Me consultar",new_consultum_path %><br><br>
      <%= button_to "Sair da Conta", paciente_logout_path, method: :delete %><br>
      <%= button_to "Apagar conta", @paciente, method: :delete %>
    </p>


</div>

app/views/acesso_paciente/new.html.erb
<p style="color: green"><%= notice %></p>

<div align="center">
  <h1>Acesso de Paciente</h1><br><br><br>

  <%= form_with url: acesso_paciente_path do |form| %>
    <div class="mb-3">
      <%= form.label :cpf %><br>
      <%= form.text_field :cpf,class:"form_control" %>
    </div>
    <div class="mb-3">
      <%= form.submit "Entrar" , class:"btn btn-primary"%>
    </div>
  <% end %>
<br>
  <br>
  <br>
  <br>
  <br>
  <%= link_to "cadastrar",new_paciente_path %>

</div>