config/routes.rb
Rails.application.routes.draw do

  resources :recepcionista
  resources :consulta do
    resources :relatorio_consulta
  end
  resources :pacientes do
    resources :endereco_paciente
  end
  resources :home
  resources :admin do
    resources :dentista
  end
  get "login", to: "login#new"
  post "login", to: "login#create"
  delete"logout", to: "login#destroy"
  get "acesso_paciente", to: "acesso_paciente#new"
  post "acesso_paciente", to: "acesso_paciente#create"
  delete"paciente_logout", to: "acesso_paciente#destroy"
  post "admin/:admin_id/dentista/new", to: "dentista#create"
  post "/consulta/:consultum_id/relatorio_consulta/new", to: "relatorio_consulta#create"
  get "acesso_recepcionista", to: "acesso_recepcionista#new"
  post "acesso_recepcionista", to: "acesso_recepcionista#create"
  delete"recepcionista_logout", to: "acesso_recepcionista#destroy"


  root to: "home#index"
end

app/views/admin/index.html.erb
<div align="center">
<h1>
  <%="Bem vindo, " + @admin.usuario + "!"%>
</h1><br><br>

<%=link_to "cadastrar dentista", new_admin_dentistum_path(@admin)%><br><br>
<%=link_to "visualizar dentistas", admin_dentista_path(@admin) ,method: :get %><br><br>
<%=link_to "cadastrar paciente",new_paciente_path  %><br><br>
<%=link_to "visualizar pacientes", "pacientes" %><br><br>
  <%=link_to "cadastrar recepcionista",new_recepcionistum_path  %><br><br>
  <%=link_to "visualizar recepcionistas", "recepcionista" %><br><br>
  <%=link_to "Agendar Consultas", new_consultum_path  %><br><br>
  <%=link_to "visualizar Consultas", "consulta" %><br><br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <%=button_to "Sair da Conta",logout_path, method: :delete %>
  <br>
  <br>
</div>