config/routes.rb
Rails.application.routes.draw do

  resources :recepcionista
  resources :consulta do
    resources :relatorio_consulta
  end
  resources :pacientes do
    resources :endereco_paciente
  end
  resources :home
  resources :admin do
    resources :dentista
  end
  get "login", to: "login#new"
  post "login", to: "login#create"
  delete"logout", to: "login#destroy"
  get "acesso_paciente", to: "acesso_paciente#new"
  post "acesso_paciente", to: "acesso_paciente#create"
  delete"paciente_logout", to: "acesso_paciente#destroy"
  post "admin/:admin_id/dentista/new", to: "dentista#create"
  post "/consulta/:consultum_id/relatorio_consulta/new", to: "relatorio_consulta#create"
  get "acesso_recepcionista", to: "acesso_recepcionista#new"
  post "acesso_recepcionista", to: "acesso_recepcionista#create"
  delete"recepcionista_logout", to: "acesso_recepcionista#destroy"


  root to: "home#index"
end

app/controllers/acesso_recepcionista_controller.rb
class AcessoRecepcionistaController < ApplicationController

  def new
  end

  def create
    @recepcionistum=  Recepcionistum.find_by(credencial: params[:credencial])
    validar_recepcionista
  end

  def destroy
    session[:recepcionistum_id] = nil
    flash[:success]="desconectado com sucesso"
    redirect_to root_path

  end

  def validar_recepcionista
    if @recepcionistum.present?
      session[:recepcionistum_id] = @recepcionistum.id
      flash[:success]= "logado com sucesso"
      render 'acesso_recepcionista/index'
    else
      flash[:alert]= "Credencial não cadastrada"
      render :'acesso_recepcionista/new'
    end
  end
end

app/views/acesso_recepcionista/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>
  <%="Bem vindo, " + @recepcionistum.nome + "!" %><br><br>
</h1>

<div id="recepcionistas">

  <p>
    <%= link_to "Ver mais informações", @recepcionistum %><br><br>
    <%= link_to "Agendar consultas",new_consultum_path %><br><br>
    <%=link_to "visualizar Consultas", "consulta" %><br><br>
    <%= button_to "Sair da Conta", recepcionista_logout_path, method: :delete %><br>
    <%= button_to "Apagar conta", @recepcionistum, method: :delete %>
  </p>


</div>

app/views/acesso_recepcionista/new.html.erb
<p style="color: green"><%= notice %></p>

<div align="center">
  <h1>Acesso de Recepcionista</h1><br><br><br>

  <%= form_with url: acesso_recepcionista_path do |form| %>
    <div class="mb-3">
      <%= form.label :credencial %><br>
      <%= form.text_field :credencial,class:"form_control" %>
    </div>
    <div class="mb-3">
      <%= form.submit "Entrar" , class:"btn btn-primary"%>
    </div>
  <% end %>

</div>