config/routes.rb
Rails.application.routes.draw do

  resources :recepcionista
  resources :consulta do
    resources :relatorio_consulta
  end
  resources :pacientes do
    resources :endereco_paciente
  end
  resources :home
  resources :admin do
    resources :dentista
  end
  get "login", to: "login#new"
  post "login", to: "login#create"
  delete"logout", to: "login#destroy"
  get "acesso_paciente", to: "acesso_paciente#new"
  post "acesso_paciente", to: "acesso_paciente#create"
  delete"paciente_logout", to: "acesso_paciente#destroy"
  post "admin/:admin_id/dentista/new", to: "dentista#create"
  post "/consulta/:consultum_id/relatorio_consulta/new", to: "relatorio_consulta#create"
  get "acesso_recepcionista", to: "acesso_recepcionista#new"
  post "acesso_recepcionista", to: "acesso_recepcionista#create"
  delete"recepcionista_logout", to: "acesso_recepcionista#destroy"


  root to: "home#index"
end

app/controllers/consulta_controller.rb
# frozen_string_literal: true

class ConsultaController < ApplicationController
  before_action :set_consultum, only: %i[show edit update destroy]

  # GET /consulta or /consulta.json
  def index
    @consulta = Consultum.all
  end

  # GET /consulta/1 or /consulta/1.json
  def show; end

  # GET /consulta/new
  def new
    @consultum = Consultum.new
    @consultas_all = Consultum.where(data: params[:data_inicial]..params[:data_final]).order(:data)
  end

  # GET /consulta/1/edit
  def edit; end

  # POST /consulta or /consulta.json
  def create
    @consultum = Consultum.new(consultum_params)
    buscar_paciente_medico

      if @consultum.save
        flash[:success]='Consulta foi criada com sucesso.'
        redirect_to "/consulta/#{@consultum.id}"
      else
        flash[:alert] = 'verifique seus campos'
        redirect_to new_consultum_path
      end
  end

  # PATCH/PUT /consulta/1 or /consulta/1.json
  def update
    respond_to do |format|
      if @consultum.update(consultum_params)
        format.html { flash[:success]='Consulta foi atualizada com sucesso'
        redirect_to consultum_url(@consultum)
        }
        format.json { render :show, status: :ok, location: @consultum }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @consultum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consulta/1 or /consulta/1.json
  def destroy
    @consultum.destroy

    respond_to do |format|
      format.html { flash[:success]='Consulta doi destruida com sucesso'
        redirect_to consulta_url}
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_consultum
      @consultum = Consultum.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def consultum_params
    params.require(:consultum).permit(:data, :horario, :paciente_id, :dentistum_id)
  end

  def buscar_paciente_medico
    if consultum_params[:paciente_id].present? and consultum_params[:dentistum_id].present?
      @paciente = Paciente.find(consultum_params[:paciente_id])
      @dentista = Dentistum.find(consultum_params[:dentistum_id])
      @paciente.consultums << @consultum
      @dentista.consultums << @consultum
    end
  end
end

app/helpers/consulta_helper.rb
module ConsultaHelper
end

app/views/consulta/_consultum.html.erb
<div id="<%= dom_id consultum %>">
  <p>
    <strong>Data:</strong>
    <%= consultum.data %>
  </p>

  <p>
    <strong>Horario:</strong>
    <%= consultum.horario %>
  </p>

  <p>
    <strong>Paciente:</strong>
    <%= consultum.paciente.nome %>
  </p>

  <p>
    <strong>Dentistum:</strong>
    <%= consultum.dentistum.nome %>
  </p>

</div>

app/views/consulta/_form.html.erb
<%= form_with(model: consultum) do |form| %>
  <% if consultum.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(consultum.errors.count, "error") %> prohibited this consultum from being saved:</h2>

      <ul>
        <% consultum.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :data, style: "display: block" %>
    <%= form.date_field :data %>
  </div>

  <div>
    <%= form.label :horario, style: "display: block" %>
    <%= form.time_field :horario %>
  </div>

  <div>
    <%= form.label :paciente_id, style: "display: block" %>
    <%= form.collection_select :paciente_id, Paciente.all, :id, :nome %>
  </div>

  <div>
    <%= form.label :dentistum_id, style: "display: block" %>
    <%= form.collection_select :dentistum_id, Dentistum.all, :id, :nome %>
  </div>

  <div><br>
    <%= form.submit %>
  </div>
<% end %>

app/views/consulta/_horario_disponivel.erb
<% if !@consultas_all.empty? %>
  <h2>Horários Indisponíveis</h2>
  <table>
    <tr>
      <th>Horario</th>
      <th></th>
      <th>Data</th>
    </tr>
    <% @consultas_all.each do |consulta| %>
      <tr>
        <td><%= consulta.horario.strftime('%H:%M') %></td>
        <td></td>
        <td><%= consulta.data.strftime('%d/%m/%Y') %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <p>Não há consultas agendadas</p>
<% end %>

app/views/consulta/edit.html.erb
<h1>Editing consultum</h1>

<%= render "form", consultum: @consultum %>

<br>

<div>
  <%= link_to "Show this consultum", @consultum %> |
  <%= link_to "Back to consulta", consulta_path %>
</div>

app/views/consulta/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Consulta</h1>

<div id="consulta">
  <% @consulta.each do |consultum| %>
    <%= render consultum %>
    <p>
      <%= link_to "Show this consultum", consultum %>
    </p>
    <br><hr>
  <% end %>

</div>

<%= link_to "New consultum", new_consultum_path %>

app/views/consulta/new.html.erb
<h1>New consultum</h1>

<%= render "form", consultum: @consultum %>

<br>

<%= render "horario_disponivel"%>

<div>
  <%= link_to "voltar pra o Menu Principal", root_path  %>
</div>

app/views/consulta/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @consultum %><br>

<div>
  <% if !@consultum.relatorio_consultum%>
    <%= link_to "gerar relatorio",  new_consultum_relatorio_consultum_path(@consultum)%><br><br>
  <% else%>
    <%= link_to "ver relatorio", "/consulta/#{@consultum.id}/relatorio_consulta/#{@consultum.relatorio_consultum.id}" %><br><br>
  <%end%>
  <%= link_to "Edit this consultum", edit_consultum_path(@consultum) %> |
  <%= link_to "Back to consulta", consulta_path %><br><br>
  <%= button_to "Destroy this consultum", @consultum, method: :delete %>
</div>